In [174]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [175]:
df=pd.read_csv("global_inflation_post_covid.csv")

In [176]:
df.head()

,country,date,inflation_rate,interest_rate,oil_price,gdp_growth,unemployment_rate,money_supply_m2,exchange_rate_usd,food_price_index,supply_chain_index
0,USA,2020-01,0.33,5.76,34.44,0.34,5.97,10558.0,69.95,94.29,3.66
1,USA,2020-02,4.12,4.33,44.75,0.02,5.80,6952.0,71.03,78.60,3.91
2,USA,2020-03,2.75,4.24,52.80,0.30,7.45,10244.0,71.00,102.91,3.70
3,USA,2020-04,4.36,4.52,39.19,2.28,5.23,9989.0,83.52,110.92,3.23
4,USA,2020-05,2.73,3.17,41.09,3.05,5.96,7982.0,70.10,86.53,3.94

In [177]:
df.tail()

,country,date,inflation_rate,interest_rate,oil_price,gdp_growth,unemployment_rate,money_supply_m2,exchange_rate_usd,food_price_index,supply_chain_index
99995,AUS,2021-07,4.577258,-0.23,74.99,3.66,7.07,10625.0,96.92,89.26,1.00
99996,TUR,2020-04,1.692581,5.71,36.33,1.45,7.13,9070.0,84.07,116.65,2.78
99997,THA,2024-09,4.363382,2.38,88.02,-1.18,5.59,16805.0,37.97,140.61,1.88
99998,PHL,2020-03,1.285730,4.04,49.48,-0.14,8.12,10400.0,26.36,94.72,3.42
99999,ZAF,2024-02,5.857930,1.90,73.09,2.77,4.08,11590.0,60.02,146.21,2.56

In [178]:
df.isna().sum()

country               0
date                  0
inflation_rate        0
interest_rate         0
oil_price             0
gdp_growth            0
unemployment_rate     0
money_supply_m2       0
exchange_rate_usd     0
food_price_index      0
supply_chain_index    0
dtype: int64

In [179]:
df.dtypes

country                   str
date                      str
inflation_rate        float64
interest_rate         float64
oil_price             float64
gdp_growth            float64
unemployment_rate     float64
money_supply_m2       float64
exchange_rate_usd     float64
food_price_index      float64
supply_chain_index    float64
dtype: object

In [181]:
x=df.drop(columns="inflation_rate")
y=df["inflation_rate"]

In [182]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [183]:
col=make_column_transformer((OneHotEncoder(handle_unknown="ignore"),["country","date"]),remainder="passthrough")

In [184]:
x=col.fit_transform(x)

In [185]:
from sklearn.model_selection import train_test_split

In [186]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=42)

In [187]:
from sklearn.linear_model import LinearRegression 
model=LinearRegression()

In [188]:
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [189]:
y_pred

array([3.50636355, 4.13107633, 3.09117374, ..., 3.84742022, 5.36589246,
       3.83864459], shape=(20000,))

In [190]:
y_test

75721    5.727327
80184    3.547616
19864    2.361425
76699    5.764029
92991    1.743205
           ...
32595    4.448137
29313    1.977439
37862    4.635492
53421    4.788421
42410    3.669145
Name: inflation_rate, Length: 20000, dtype: float64

In [191]:
model.coef_

array([-7.13018535e-01, -4.23430949e-01, -2.95752654e-01, -9.02329812e-02,
       -7.44573750e-01, -9.00048065e-01,  3.75510654e-01, -3.71550982e-01,
        1.39417989e+00, -2.81501799e-01,  1.34067045e+00,  9.07911112e-01,
       -1.46512114e+00,  3.93238172e-01,  9.44007979e-01, -1.51193333e+00,
        1.27391227e-01, -1.19760216e-01,  3.56618712e-01,  1.07739622e+00,
       -5.77499900e-01,  1.68782561e-01, -2.40351488e-01,  1.21629235e-01,
        1.06304346e-01,  1.58920809e-01,  1.68082671e-01,  6.30920072e-02,
       -2.03341387e-02, -1.10537014e-01, -4.65024776e-03,  1.90786778e-01,
       -1.32252448e-01, -4.66605555e-01,  2.63935480e-01,  2.11851077e-01,
       -8.30707311e-02,  1.74515473e-01, -3.00516249e-01, -2.68919962e-01,
       -3.66076011e-02,  1.45115937e-01,  1.28799758e-02,  1.22262306e-02,
       -1.66347940e-01,  5.23700475e-02, -2.14639425e-01,  2.31822512e-03,
       -1.45448154e-01,  1.12735421e-02,  9.08435603e-02, -5.33937635e-03,
        2.82886846e-01,  8.53710658e-02, -7.21799591e-02,  3.47623928e-03,
        3.76668596e-01,  1.67008063e-01,  1.04857645e-01,  1.19095131e-01,
        2.45106909e-01, -5.92907798e-02, -3.09684100e-01, -4.75614246e-01,
        3.98144434e-02,  1.11863976e-01,  7.83703683e-02,  3.30757908e-01,
       -2.98647660e-01, -1.06904150e-02,  2.28346734e-01,  1.98482870e-02,
        7.64060436e-02,  1.42158256e-01, -3.32828725e-01, -8.13156756e-02,
       -3.90304796e-02,  3.91064122e-01,  1.12396085e-01, -4.18022404e-01,
       -2.80331849e-01,  2.09745210e-02,  2.87725348e-03,  2.39725279e-02,
        3.15884264e-05, -4.06207352e-03, -2.57093131e-03,  4.50706330e-01])

In [192]:
model.intercept_

np.float64(2.4293998612264223)

In [193]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error,r2_score

In [194]:
print(mean_absolute_error(y_test,y_pred))

0.8633988691495411

In [195]:
print(mean_squared_error(y_test,y_pred))

1.1924297234125891

In [196]:
print(root_mean_squared_error(y_test,y_pred))

1.091984305479062

In [197]:
print(r2_score(y_test,y_pred))

0.43811046793424957