In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("global_inflation_post_covid.csv")

In [3]:
df.head()

,country,date,inflation_rate,interest_rate,oil_price,gdp_growth,unemployment_rate,money_supply_m2,exchange_rate_usd,food_price_index,supply_chain_index
0,USA,2020-01,0.33,5.76,34.44,0.34,5.97,10558.0,69.95,94.29,3.66
1,USA,2020-02,4.12,4.33,44.75,0.02,5.80,6952.0,71.03,78.60,3.91
2,USA,2020-03,2.75,4.24,52.80,0.30,7.45,10244.0,71.00,102.91,3.70
3,USA,2020-04,4.36,4.52,39.19,2.28,5.23,9989.0,83.52,110.92,3.23
4,USA,2020-05,2.73,3.17,41.09,3.05,5.96,7982.0,70.10,86.53,3.94

In [4]:
df.tail()

,country,date,inflation_rate,interest_rate,oil_price,gdp_growth,unemployment_rate,money_supply_m2,exchange_rate_usd,food_price_index,supply_chain_index
99995,AUS,2021-07,4.577258,-0.23,74.99,3.66,7.07,10625.0,96.92,89.26,1.00
99996,TUR,2020-04,1.692581,5.71,36.33,1.45,7.13,9070.0,84.07,116.65,2.78
99997,THA,2024-09,4.363382,2.38,88.02,-1.18,5.59,16805.0,37.97,140.61,1.88
99998,PHL,2020-03,1.285730,4.04,49.48,-0.14,8.12,10400.0,26.36,94.72,3.42
99999,ZAF,2024-02,5.857930,1.90,73.09,2.77,4.08,11590.0,60.02,146.21,2.56

In [5]:
df.isna().sum()

country               0
date                  0
inflation_rate        0
interest_rate         0
oil_price             0
gdp_growth            0
unemployment_rate     0
money_supply_m2       0
exchange_rate_usd     0
food_price_index      0
supply_chain_index    0
dtype: int64

In [6]:
df.dtypes

country                   str
date                      str
inflation_rate        float64
interest_rate         float64
oil_price             float64
gdp_growth            float64
unemployment_rate     float64
money_supply_m2       float64
exchange_rate_usd     float64
food_price_index      float64
supply_chain_index    float64
dtype: object

In [7]:
x=df.drop(columns="inflation_rate")
y=df["inflation_rate"]

In [8]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [9]:
col=make_column_transformer((OneHotEncoder(handle_unknown="ignore"),["country","date"]),remainder="passthrough")

In [10]:
x=col.fit_transform(x)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=42)

In [13]:
from sklearn.linear_model import LinearRegression 
model=LinearRegression()

In [14]:
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [15]:
y_pred

array([3.50636355, 4.13107633, 3.09117374, ..., 3.84742022, 5.36589246,
       3.83864459], shape=(20000,))

In [16]:
y_test

75721    5.727327
80184    3.547616
19864    2.361425
76699    5.764029
92991    1.743205
           ...
32595    4.448137
29313    1.977439
37862    4.635492
53421    4.788421
42410    3.669145
Name: inflation_rate, Length: 20000, dtype: float64

In [17]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error,r2_score

In [18]:
print(mean_absolute_error(y_test,y_pred))

0.8633988691495411

In [19]:
print(mean_squared_error(y_test,y_pred))

1.1924297234125891

In [20]:
print(root_mean_squared_error(y_test,y_pred))

1.091984305479062

In [21]:
print(r2_score(y_test,y_pred))

0.43811046793424957