In [113]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [114]:
df=pd.read_csv("student-mat.csv")

In [115]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [116]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [117]:
df.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [118]:
df.dtypes

school          str
sex             str
age           int64
address         str
famsize         str
Pstatus         str
Medu          int64
Fedu          int64
Mjob            str
Fjob            str
reason          str
guardian        str
traveltime    int64
studytime     int64
failures      int64
schoolsup       str
famsup          str
paid            str
activities      str
nursery         str
higher          str
internet        str
romantic        str
famrel        int64
freetime      int64
goout         int64
Dalc          int64
Walc          int64
health        int64
absences      int64
G1            int64
G2            int64
G3            int64
dtype: object

In [119]:
df=df.drop_duplicates()

In [120]:
x=df.drop(columns="G3")
y=df["G3"]

In [121]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [122]:
col=make_column_transformer((OneHotEncoder(handle_unknown="ignore"),["school","sex","address","famsize","Pstatus","Mjob","Fjob","reason","guardian","schoolsup","famsup","paid","activities","nursery","higher","internet","romantic"]),remainder="passthrough")

In [123]:
x=col.fit_transform(x)

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=42)

In [126]:
from sklearn.linear_model import LinearRegression

In [127]:
model=LinearRegression()

In [128]:
model.fit(x_train,y_train)

LinearRegression()

In [129]:
y_pred=model.predict(x_test)
y_pred

array([ 6.00160699, 11.52847844,  2.86643677,  8.79663116,  8.55310627,
       11.88964112, 19.09674195,  7.17307901,  7.4050707 , 12.31153657,
       14.50202689,  5.52448201, 13.64498491, 11.94484589, 14.6379871 ,
        8.46898698,  5.84105527, 10.75365252, 14.22958393,  8.40257994,
       13.79124386, 16.35136154, 13.5710786 ,  5.88531485,  8.40557156,
       20.82262969, 10.55231057,  9.277694  , 17.11938646, 11.58080009,
        9.38983351,  6.68701138, 14.43529558, 12.78113257,  5.32339752,
        4.15398128, -2.57739105, 15.53366365, 12.09668779,  6.57159416,
        5.45294413,  9.83775897, 14.48014104,  6.91378509, 16.88534513,
        9.17660623, 11.3471303 , 13.7703158 , 11.05012149, 15.87344331,
       14.00504973, 14.33550256,  9.72665558,  7.37608193,  3.26326232,
       12.69215949, 10.45929549,  6.45503769, 15.59150316, 16.00262765,
       13.54350243,  7.61990637,  8.10361767,  4.06225543,  3.1583286 ,
       16.3610109 ,  7.9314948 ,  8.31470193,  9.19538486, 16.23839817,
        8.24081518,  8.58890771, 13.8883608 , 20.47747752, 10.15673983,
        6.27578808,  7.68665599, 12.40906664,  4.33817439])

In [130]:
y_test

78     10
371    12
248     5
55     10
390     9
       ..
364    12
82      6
114     9
3      15
18      5
Name: G3, Length: 79, dtype: int64

In [131]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,root_mean_squared_error

In [132]:
print(mean_squared_error(y_test,y_pred))

5.65664283323122

In [133]:
print(mean_absolute_error(y_test,y_pred))

1.64666561971475

In [134]:
print(r2_score(y_test,y_pred))

0.7241341236974023

In [135]:
print(root_mean_squared_error(y_test,y_pred))

2.3783697847961363