In [192]:
import pandas as pd
import numpy as np

In [193]:
df=pd.read_csv("heart__missing.csv")

In [194]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,1.0,0.0,125.0,212.0,0.0,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0
1,53.0,NaN,0.0,140.0,203.0,NaN,NaN,155.0,1.0,3.1,0.0,0.0,3.0,0
2,NaN,1.0,0.0,145.0,174.0,0.0,1.0,125.0,1.0,NaN,0.0,NaN,3.0,0
3,61.0,1.0,0.0,148.0,203.0,0.0,1.0,NaN,0.0,0.0,2.0,1.0,3.0,0
4,62.0,0.0,NaN,NaN,NaN,1.0,1.0,106.0,0.0,NaN,1.0,3.0,2.0,0

In [195]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59.0,1.0,1.0,140.0,221.0,0.0,1.0,164.0,1.0,0.0,2.0,NaN,2.0,1
1021,60.0,1.0,0.0,125.0,258.0,0.0,0.0,141.0,1.0,NaN,1.0,1.0,3.0,0
1022,47.0,1.0,NaN,NaN,275.0,0.0,0.0,NaN,1.0,NaN,NaN,1.0,2.0,0
1023,50.0,0.0,0.0,110.0,254.0,0.0,NaN,159.0,0.0,0.0,2.0,0.0,2.0,1
1024,54.0,1.0,0.0,120.0,188.0,0.0,1.0,113.0,0.0,1.4,1.0,1.0,NaN,0

In [196]:
df.isna().sum()

age         156
sex         144
cp          183
trestbps    145
chol        150
fbs         156
restecg     148
thalach     143
exang       163
oldpeak     159
slope       154
ca          150
thal        148
target        0
dtype: int64

In [197]:
cate=["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal"]

In [198]:
for  i  in cate:
    df[i]=df[i].fillna(df[i].mean())

In [199]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [200]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

In [201]:
df=df.drop_duplicates()

In [202]:
x=df.drop(columns="target")
y=df["target"]

In [203]:
from sklearn.model_selection import train_test_split

In [204]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=42)

In [205]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [206]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

knn=KNeighborsClassifier(n_neighbors=5)
svm=SVC()
naive=GaussianNB()

In [207]:
lst=[knn,svm,naive]

for i in lst:
    print("model selection______________",i)
    print(i.fit(x_train,y_train))
    y_pred=i.predict(x_test)

    print("confusion matrix______________",i)
    print(confusion_matrix(y_pred,y_test))

    print("accuracy score________________",i)
    print(accuracy_score(y_pred,y_test))

model selection______________ KNeighborsClassifier()
KNeighborsClassifier()
confusion matrix______________ KNeighborsClassifier()
[[106   8]
 [ 24 115]]
accuracy score________________ KNeighborsClassifier()
0.8735177865612648
model selection______________ SVC()
SVC()
confusion matrix______________ SVC()
[[110  10]
 [ 20 113]]
accuracy score________________ SVC()
0.8814229249011858
model selection______________ GaussianNB()
GaussianNB()
confusion matrix______________ GaussianNB()
[[101  20]
 [ 29 103]]
accuracy score________________ GaussianNB()
0.8063241106719368