In [951]:
import pandas as pd
import pandas as np
import matplotlib.pyplot as plt

In [952]:
df=pd.read_csv("used_car_dataset.csv")

In [953]:
df.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"

In [954]:
df.tail()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
9577,Skoda,Octavia,2014,10,"105,904 km",Automatic,second,Diesel,Oct-24,"Skoda Octavia 1.9 Elegance TDI, 2014, Diesel","₹ 10,40,000"
9578,Maruti Suzuki,Alto-800,2020,4,"55,000 km",Manual,first,Hybrid/CNG,Nov-24,"Maruti Suzuki Alto 800 CNG LXI Optional, 2020,...","₹ 3,75,000"
9579,Maruti Suzuki,Ritz,2013,11,"92,000 km",Manual,first,Diesel,Nov-24,"Maruti Suzuki Ritz VDi, 2013, Diesel","₹ 4,15,000"
9580,Hyundai,Verna,2019,5,"72,000 km",Automatic,first,Petrol,Oct-24,"Hyundai Verna VTVT 1.6 AT SX Option, 2019, Petrol","₹ 8,55,000"
9581,Hyundai,New i20,2021,3,"83,228 km",Manual,second,Petrol,Nov-24,"Hyundai New i20 1.2 Asta IVT, 2021, Petrol","₹ 6,99,000"

In [955]:
df.shape

(9582, 11)

In [956]:
df.isnull().sum()

Brand            0
model            0
Year             0
Age              0
kmDriven        47
Transmission     0
Owner            0
FuelType         0
PostedDate       0
AdditionInfo     0
AskPrice         0
dtype: int64

In [957]:
df["kmDriven"]=df["kmDriven"].str.replace("km","").str.replace(",","")

In [958]:
df["kmDriven"]=df["kmDriven"].astype("float")

In [959]:
df["kmDriven"]=df["kmDriven"].fillna(df["kmDriven"].median())

In [960]:
df.drop(columns=["Brand","PostedDate","AdditionInfo"],inplace=True)

In [961]:
df.isna().sum()

model           0
Year            0
Age             0
kmDriven        0
Transmission    0
Owner           0
FuelType        0
AskPrice        0
dtype: int64

In [962]:
df.dtypes

model               str
Year              int64
Age               int64
kmDriven        float64
Transmission        str
Owner               str
FuelType            str
AskPrice            str
dtype: object

In [963]:
from sklearn.preprocessing import LabelEncoder

In [964]:
le=LabelEncoder()

In [965]:
df["FuelType"]=le.fit_transform(df["FuelType"])

In [966]:
df["Owner"]=le.fit_transform(df["Owner"])

In [967]:
df["model"]=le.fit_transform(df["model"])

In [968]:
df["Transmission"]=le.fit_transform(df["Transmission"])

In [969]:
df["AskPrice"]=df["AskPrice"].str.replace("₹","")
df["AskPrice"]=df["AskPrice"].str.replace(",","")
df["AskPrice"]=df["AskPrice"].astype("float")

In [970]:
df.dtypes

model             int64
Year              int64
Age               int64
kmDriven        float64
Transmission      int64
Owner             int64
FuelType          int64
AskPrice        float64
dtype: object

In [971]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [972]:
from sklearn.model_selection import train_test_split

In [973]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=10)

In [974]:
from sklearn.preprocessing import StandardScaler

In [975]:
scaler=StandardScaler()

In [976]:
scaler.fit(x_train)

StandardScaler()

In [977]:
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [978]:
from sklearn.neighbors import KNeighborsRegressor

In [979]:
model=KNeighborsRegressor(n_neighbors=5)

In [980]:
model.fit(x_train,y_train)

KNeighborsRegressor()

In [981]:
y_pred=model.predict(x_test)

In [982]:
from sklearn.metrics import mean_absolute_error

In [983]:
mae=mean_absolute_error(y_test,y_pred)

In [984]:
from sklearn.metrics import r2_score

In [985]:
r2_score(y_test,y_pred)

0.2561636879720429